config/routes.rb
	Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'keshbacks#index'

  resources :keshbacks
	resources :comments, only: %i[create destroy]
	resources :users,    only: %i[index show]
	get 'pages/about', to: 'pages#about'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  attr_accessor :login

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(['lower(email) = :value OR lower(email) = :value', { value: login.strip.downcase }]).first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :keshback

  validates :text, presence: :true
end

app/models/keshback.rb
class Keshback < ApplicationRecord
  belongs_to :user,       optional: true

  has_many :comments,     dependent: :destroy

  validates :name,        presence: true
  validates :count,       presence: true
  validates :link,        presence: true
  validates :description, presence: true
  mount_uploader :photo,  PhotoUploader

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :keshbacks, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, default_url: '/assets/missing.png'
  validates_attachment_content_type :avatar, content_type: ['image/jpeg', 'image/gif', 'image/png']

  validates :nickname, presence: :true, uniqueness: { case_sensitive: false }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(['lower(nickname) = :value OR lower(email) = :value', { value: login.strip.downcase }]).first
  end

  def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, _error = :invalid)
    (case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }

    attributes = attributes.slice(*required_attributes)
    attributes.delete_if { |_key, value| value.blank? }

    if attributes.keys.size == required_attributes.size
      if attributes.key?(:login)
        login = attributes.delete(:login)
        record = find_record(login)
      else
        record = where(attributes).first
      end
    end
  end

  def self.find_record(login)
    where(['username = :value OR email = :value', { value: login }]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname email password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[login password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar nickname email password password_confirmation current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment = current_user.comments.build(comment_params)
    redirect_back(fallback_location: root_path) if comment.save
  end

  def destroy
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :text, :keshback_id)
  end

  def comment
    @comment ||= current_user.comments.find_by(id: params[:id])
    @comment ||= Comment.new
  end
end

app/controllers/keshbacks_controller.rb
class KeshbacksController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_keshback, only: %i[show edit update destroy]

  def index
    @keshbacks = Keshback.all
  end

  def new
    @keshback = Keshback.new
  end

  def create
    @keshback = current_user.keshbacks.build(keshback_params)
  if @keshback.save
    redirect_to keshback_path(@keshback.id)
  else
    render 'new'
  end
  end

  def show
    @comments=Comment.where(keshback_id: @keshback.id).order(created_at: :desc)
  end

  def edit
  #  if  @keshback.user == nil#if create admin
       # if create user  && @keshback.user.id != current_user.id
  #    redirect_to keshback_path(@keshback.id)
#    end

  end

  def update
   if @keshback.update(keshback_params)
     redirect_to keshback_path(@keshback.id)
    else render 'edit'
   end
  end

  def destroy
  if @keshback.present?
      @keshback.destroy
  end
    redirect_to root_path
   end

  private

  def find_keshback
    @keshback = Keshback.find_by(id: params[:id])
  end

  def keshback_params
    params.require(:keshback).permit(:user_id, :name, :link,:count,:description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'Страница про нас!'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/keshbacks_helper.rb
module KeshbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
Author:
<%= link_to user_path(comment.user.id) do %><br>
<%= comment.user.nickname%><br>
<%= image_tag comment.user.avatar.url, style:"width:100px;"%><br>
<%end%>
Text:
<br>
<%=comment.text%><br>
Created:
<%= comment.created_at.to_date.strftime("%d %B, %Y") %>

<% if user_signed_in? && comment.user.id == current_user.id %>
<br>
<%= link_to "delete", comment_path(comment.id), method: :delete %>
<% end%>
<hr>

app/views/comments/_form.html.erb
<%= form_for :comment, url: comments_path do |f| %>
<%= f.text_area :text, class: "form-control", :rows => 4 %>
<%= f.hidden_field :keshback_id, value: @keshback.id %>
<%= f.submit "Comment", class:"btn btn-primary" %>
<%end%>

app/views/keshbacks/_form.html.erb
<% if @keshback.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@keshback.errors.count, "error") %>
      prohibited this keshback from being saved:</h2>

    <ul>
      <% @keshback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group ">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder:"Введіть назву кешбека:" %>
</div>
<div class="form-group ">
  <%= f.label :count %>
  <%= f.text_field :count, class: "form-control", placeholder:"Введіть велечинину кешбека:" %>
</div>
<div class="form-group ">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", placeholder:"Введіть опис кешбеку:" %>
</div>
<div class="form-group ">
  <%= f.label :link %>
  <%= f.text_field :link, class: "form-control", placeholder:"Введіть посилання на сайт:" %>
</div>
<div class="form-group">
  <%= f.label :photo %>
  <%= f.file_field :photo, class:"form-control-file" %>

</div>

app/views/keshbacks/_keshback_card.html.erb
<div class='keshback-card'>
  <h6>
    <%= link_to keshback do %>
    <%= keshback.name[0..13] ...%>
  <% end %>
</h6>
<%= link_to keshback do %>
<img style='width: 100px;' src='<%= keshback.photo %>' alt=''/>
<% end %>
<h5>
+/-
<%= keshback.count %>
%
</h5>
<p>
<%= link_to "Link", "https://#{keshback.link}" %>
</p>
<% if !local_assigns.has_key?(:hide_form) || !hide_form %>
<div class='row'>
  <div class='col-md-6'>
    <%= link_to keshback, class: 'btn btn-light' do %>
    Read More
  <% end %>
</div>
</div>
<% end %>
<%= yield %>
</div>
<br>

app/views/keshbacks/_keshbacks_list.html.erb
<% keshbacks.each_slice(12) do | keshbacks_group | %>
  <div class='row'>
    <% keshbacks_group.each do |keshback| %>
      <div class='col-sm-2 col-xs-4'>
        <%= render 'keshback_card', keshback: keshback %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/keshbacks/edit.html.erb
<center><div class="col-md-6 col-md-offset-3 login-box">
<%= form_for @keshback, url: keshback_path(@keshback.id) do |f| %>
<%= render 'keshbacks/form', f:f%>
<%= f.submit "Update", class:"btn btn-warning"%>
<% end %>
</div>
</center>

app/views/keshbacks/index.html.erb
<div class='album'>
  <div class='container'>
    <%= render 'keshbacks_list', keshbacks: @keshbacks %>
  </div>
</div>

app/views/keshbacks/new.html.erb
<center><div class="col-md-6 col-md-offset-3 login-box">
<%= form_for @keshback, url: keshbacks_path do |f| %>
<%= render 'keshbacks/form', f:f%>
<%= f.submit "Create", class:"btn btn-primary"%>
<% end %>
</div>
</center>

app/views/keshbacks/show.html.erb
<div class='album'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-6 text-center mb-sm-5'>
        <img style='max-width: 100%;' src='<%= @keshback.photo %>' alt=''/>
      </div>
      <div class='col-md-6 mb-sm-5'>
        <div class='card'>
          <div class='card-body'>
            <div class="row">

              <% if user_signed_in? &&  @keshback.user != nil && @keshback.user.id == current_user.id %>
                <div class="col">
                  Бажаєте відредагувати?
                  <%= link_to "Edit", edit_keshback_path(@keshback.id),class:"btn btn-warning"%>
                </div>
                <div class="col">
                  Щось пішло не так? Видалити?
                  <%= link_to "Delete", keshback_path(@keshback.id), method: :delete, class:"btn btn-danger"%>
                </div>
              <%end%>
            </div>
            <h1>
              <%= @keshback.name %>
            </h1>
            <p>
              <%= link_to "Link", "https://#{@keshback.link}" %>
            </p>
            <h5>
              <%= @keshback.count %>
              %
            </h5>
            <% if user_signed_in? %>

              <%= render 'comments/form'%>

            <% else %>
              <%= link_to "Reg", new_user_registration_path%><br>
              або
              <%= link_to "Log", new_user_session_path%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class='mb-sm-5'>
      <%= @keshback.description %>
    </div>
  </div>
  <ul class="content-list content-list_comments">
    <% @comments.each do |comment| %>
      <%=render 'comments/comment', comment:comment %>
    <%end%>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm">
  <%= link_to "Freshback", root_path, class:"navbar-brand" %>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "All Freshbacks", keshbacks_path, class:"nav-link" %>
    </li>
    <%if user_signed_in?%>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", user_path(current_user.id), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Freshback", new_keshback_path, class:"nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Registration", new_user_registration_path, class:"nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fresh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h4> <%= @heading %> <h4>

app/views/users/index.html.erb
All users:
<br>
<div class='album'>
  <div class='container'>
    <% @users.each_slice(3) do | y | %>
      <div class='row'>
        <% y.each do |x| %>
          <div class='col-sm-4 col-xs-4'>
            <div class="card">
              <img class="card-img-top" src="<%= x.avatar.url %>" alt="Card image">
              <div class="card-body">
                <h4 class="card-title"><%= x.nickname %></h4>
                <p class="card-text"><%= x.email%></p>
                <%= link_to "Profile", user_path(x.id), class:"btn btn-primary"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<center>
  <div class='col-sm-4 col-xs-4'>
    <div class="row">
      <div class="col">
        <div class="text-center">
          <%= image_tag @user.avatar.url,style:"max-width:400px;" %><br>
          <%= @user.nickname%>
          <br>
          <%= @user.email%>
          <% if user_signed_in? && @user == current_user %>
            <hr>
            <%= link_to "Setting", edit_user_registration_path, class:"btn btn-warning"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</center>